#!/bin/bash 

test_backend() {
  URL=$1
  BACKEND=$2
  TEST_NUM=$((TEST_NUM+1))

  info "Run test #${TEST_NUM}."
  result=$(wget -q -O - ${HOST}${URL} 2>&1) || error "GET request for ${URL} failed"

  if [[ $result = *"${URL}"*"${BACKEND}"* ]]; then
    echo -e "  \033[32mPass! Correct backend ${BACKEND} used.\033[39m"
    SUCCESS_NUM=$((SUCCESS_NUM+1))
  else
    echo -e "  \033[91mFailed! Expect backend ${BACKEND}!\033[39m"
    FAILED_NUM=$((FAILED_NUM+1))
    EXIT_CODE=1
  fi
  echo
}
