#!/bin/bash -e

cd $(dirname $0)/..

IMAGE="nexus.example.com:8082/showerlee/ansible:2.9"

exec docker run -i \
    --volume ${PWD}/ansible:/cwd \
    --volume /etc/hosts:/etc/hosts \
    --volume ~/.ssh:/root/.ssh \
    --workdir /cwd \
    "${IMAGE}" "$@"
