#!/bin/bash -e

cd $(dirname $0)/..
source ./auto/set-env-vars

exec docker run -i \
    --volume ${PWD}/ansible:/cwd \
    --volume /etc/hosts:/etc/hosts \
    --volume ~/.ssh:/root/.ssh \
    --workdir /cwd \
    "${ANSIBLE_DOCKER_IMAGE}:${ANSIBLE_VERSION}" "$@"
