#! /bin/bash -e

cd $(dirname $0)/..
source ./auto/set-env-vars

PROJECT_NAME=$1
DEPLOY_ENV=$2
NEXUS_USERNAME=$3
NEXUS_PASSWORD=$4
NEXUS_URL=$5

echo "[INFO] Start ansible deployment via docker"
auto/ansible ansible-playbook \
    -i "inventory/${DEPLOY_ENV}" \
    "./deploy.yml" \
    -e project="${PROJECT_NAME}" \
    -e nexus_user="${NEXUS_USERNAME}" \
    -e nexus_pass="${NEXUS_PASSWORD}" \
    -e nexus_url="${NEXUS_URL}" \
    -e app_image="$(cat artifacts/docker-image-released.txt)"

