#!/bin/bash -e

ENV=$1
PORT=$2
PROJECT=$3

DOMAIN="www.${ENV}.example.com"

curl -Is http://$DOMAIN:$PORT/$PROJECT/ > /dev/null && echo "[INFO] The remote site http://$DOMAIN:$PORT/$PROJECT/ is healthy and good to go..." || echo "[INFO] The remote side is failed, please check..."
