#! /bin/bash -e

cd $(dirname $0)/..
source ./auto/set-env-vars

export VERSION=dev-$(date +'%Y%m%d%H%M')
auto/build $VERSION

# Release ansible to new registry
docker push ${ANSIBLE_DOCKER_IMAGE}:${ANSIBLE_VERSION}
docker tag ${ANSIBLE_DOCKER_IMAGE}:${ANSIBLE_VERSION} ${ANSIBLE_DOCKER_IMAGE}:latest
docker push ${ANSIBLE_DOCKER_IMAGE}:latest

# Release app to new registry
docker push ${DOCKER_IMAGE}:${VERSION}
docker tag ${DOCKER_IMAGE}:${VERSION} ${DOCKER_IMAGE}:latest
docker push ${DOCKER_IMAGE}:latest

# Save app image reference
mkdir -pv artifacts
DIGEST=$(docker pull ${DOCKER_IMAGE}:${VERSION} | sed -n 's/^Digest: // p')
IMAGE="${DOCKER_IMAGE}:${VERSION}@${DIGEST}"
echo "$IMAGE" > artifacts/docker-image-released.txt
echo "Released as: $IMAGE"
