#!/bin/bash -e

export WORKING_DIR="/app"
export APP_NAME="gradle-demo-with-docker"
export PACKAGE_NAME="showerlee/gradle-demo-with-docker"
export REPOSITORY="nexus.example.com"
export REPO_PORT="8082"
export DOCKER_IMAGE="${REPOSITORY}:${REPO_PORT}/${PACKAGE_NAME}"
export APP_PORT="8083"
export ANSIBLE_VERSION="2.9"
export ANSIBLE_PACKAGE_NAME="showerlee/ansible"
export ANSIBLE_DOCKER_IMAGE="${REPOSITORY}:${REPO_PORT}/${ANSIBLE_PACKAGE_NAME}"

display_status() {
    echo ">>> $1 <<<" 1>&2
}

