#!/bin/bash -e

USER=$1
ENV=$2
PORT=$3

DOMAIN="www.${ENV}.example.com"

declare -i n=1

while ((n<=3))
do
  STATUS=$(ssh -o BatchMode=yes -o ConnectTimeout=5 -p$3 ${USER}@${DOMAIN} echo ok 2>&1)
  if [[ ${STATUS} == ok ]]; then
    echo [INFO] sshd is listening on port $3
  elif [[ ${STATUS} == "Permission denied"* ]] ; then
    echo authentication failed, please check.
  else
    echo ${STATUS}
  fi
  let ++n
  sleep 3
done

if [[ ${STATUS} == ok ]]; then
  echo "[INFO] ssh connection available, it is good to go."
else
  echo "[INFO] ssh connection failed, please check."
  exit 1
fi
