- name: Install docker
  yum: name=docker state=latest  

- name: Startup docker
  service: name=docker state=restarted

- name: Install python-pip
  yum: name=python-pip state=latest

- name: Install python docker api
  shell: "pip install docker"

- name: Stop a container
  docker_container:
    name: "{{ project }}"
    state: stopped

- name: Remove APP image
  shell: "docker rmi $(docker images | grep {{ project }} | awk '{print $3}')"

- name: Log into DockerHub
  docker_login:
    registry: "{{ nexus_url }}"
    username: "{{ nexus_user }}"
    password: "{{ nexus_pass }}"
    reauthorize: yes

- name: "Spinup {{project}} docker container"
  docker_container:
    name: "{{ project }}"
    image: "{{ app_image }}"
    ports:
    - "8083:8080"
  when: project == "gradle-demo-with-docker"

- name: pause 5 seconds
  pause: seconds=5

- name: Run tomcat health check locally
  shell: "sh roles/deploy/files/health-check.sh {{ site_url }} {{ port }} {{ project }}"
  delegate_to: localhost
  register: health_status

- debug: msg="{{ health_status.stdout }}"

